### PR TITLE
Support `default` in options

### PR DESCRIPTION
**Pull request by Acathur**

### CODE REVIEW

**Comment by jozsefsallai** [comment]
I'm a bit reluctant on the `:` change. I feel like we should let the user choose whether they want to end the message in a colon or something else.

For example, with your modification, a message that equals `What's your name?` would result in `What's your name?:`, which is a bit awkward, I think.

The `default` option is a very good addition though! Thank you very much :)

**Comment by Acathur** [comment]
It makes sense. Maybe adding a `suffix` option (default to `''`) will solve this problem.
Also, I just checked inquirer [code](https://github.com/SBoudrias/Inquirer.js/blob/af16d5b44cb040c7faa69983a7e088f617141644/packages/inquirer/lib/prompts/base.js#L36-L39), do you think add a trailing colon to `name` is necessary when the `message` is not defined? @jozsefsallai

**Comment by jozsefsallai** [comment]
I like that idea, yeah!

> do you think add a trailing colon to `name` is necessary when the `message` is not defined?

Yeah, that would be neat! You could check if `!opts.message && opts.prefix === undefined` is true, then set the suffix to `:`. This way the user can opt-out of having a colon if they want (that sounds so bad out of context) when `message` is missing, by passing `prefix: ''` to the opts.

**Comment by Acathur** [comment]
> You could check if `!opts.message && opts.prefix === undefined` is true, ...

I'm a little confused, is that a typo? I think we should check `opts.suffix` instead.

**Comment by jozsefsallai** [comment]
Yep, it was a typo. My bad!

**Comment by Acathur** [comment]
@jozsefsallai check it out, bro

**Comment by jozsefsallai** [comment]
Thank you!

**Pull request merged**
